# Generated by Django 3.2.9 on 2021-11-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20211115_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cotetnt',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
